language: node_js
node_js:
- '7'
script:
- ng build
deploy:
  provider: heroku
  buildpack: https://github.com/heroku/heroku-buildpack-static.git
  api_key:
    secure: RLDUQMvKFAeZ0JXhzpZzyXbSFYX+m673+qKUdZ+lRaZduSSUz2RxDkh2w0pvGwLYGbmnA4GXkPWOn0jAVmDSxO08Jg03BWjm6rDZtBcKE2Oz6LOOV02WwvCDXFx0iR9VbztYNXtRkZX8YCeKArb4rLepI2l5qfUA1DipUBdsW+QxCuY27TOwnn83nuaCJJnBlwFsRqXwpc6Nn6pPAepVx53GdG33aQllugUF8ibkRC/7S33BbPr3d/Fh6nH2HhJis96sWtY6/arZE8uL0LIgFqbbNdTaeZfHPpMk8J68aFPevCo2jGYjQaz4qIdBzKS/95D6iQChrFH1vIpP3yCKiP0P5xE1vnorC5Z09oNqSYq9AuJeObvO7tHHFRnXUfDa5a6fIcK4BhVx2/TAByvGxOCwiBdbG2rTvVIRa8ZMiOwP5Z+CIkmrg6XbJExRSwDscP/s+gPoDFoFlqUgSGE+rR7Hd2QEjHFcxf+Ar/9obbguyd3Yw9VVznaoB6/aseub0MLpR3gNrXNfpnbPhp9QWAIJ8NSZC5HzvBnxcQCJcjtvebVenHi6fqLM2cSKiw9Nvl8LKfyDl27wFyFFVkB+aKXLHfWP/AZ3Dqssn/tswrz524ATNW3Kv21GYLB8IcgJH5uKCnDJcc99y91jpnzkslmSGSJO/Z8rrXE9rEpYefk=
  app: brunaelair
  on:
    repo: lairjr/brunaelair
